[workspace]
resolver = "2"
members = ["crates/apps/*", "crates/libs/*", "examples/*"]

[workspace.dependencies]
openapi_schema = { path = "crates/libs/openapi_schema" }

openapiv3 = { version = "2.0.0" }
