[package]
name = "openapi_kit_renderer"
description = "OpenAPI Renderer"
version = "0.0.8"
edition = "2024"
homepage = "https://github.com/netrune/openapi"
repository = "https://github.com/netrune/openapi"
readme = "README.md"
license = "MIT"

[dependencies]
openapi_kit_schema.workspace = true
openapi_kit_workspace.workspace = true
serde.workspace = true
tera = { version = "1.20.0" }
